[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
blinkbuy = "AkcuJCPFYioPG7yq1k9igMHF7SapejrFE6TbAX4oDxxL"

[registry]
url = "devnet"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
